apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: amnodejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: amnodejs
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70