apiVersion: v1
kind: Service
metadata:
  name: amnodejs_svc
spec:
  selector:
    app: amnodejs
  ports:
  - port: 80
    targetPort: 4000
---

apiVersion: v1
kind: apiVersion: apps/v1
kind: Statefulset

metadata:
  name: amnodejs
  environment: production
spec:
  selector:
    matchLabels:
      app: amnodejs
  template:
    metadata:
      labels:
        app: amnodejs
    spec:
      containers:
      - name: amnodejs
        image: gcr.io/buoyant-genre-251705/amnodejs:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: <Port>


