
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-file-log
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  path: /dev/stdout
plugin: file-log