apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: dennis
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: dennis
credentials:
  - dennis-apikey